🚧 DRAFT 🚧 - initial implementation (iss. #1)
tl-its-umich-edu/peer-review-data pull request #2
Opened 2022-11-29 21:33 UTC by lsloan

2022-12-01 21:17 UTC, lsloan commented
@zqian: This PR isn't ready for review, but I know you like to see how the project is progressing.  You can give suggestions if you like, but keep in mind this is a work in progress.

2022-12-20 17:24 UTC, zqian requested changes

2022-12-20 17:24 UTC, zqian commented on docker-compose.yaml
> +      - .env
Need to provide a sample .env file. I cannot get docker-compose started for testing.

2022-12-23 17:50 UTC, zqian commented
I can test the code now with params for Canvas test server. I think the test plan instructions in this PR can be added into the README file.

2023-01-03 21:03 UTC, lsloan commented
@zqian, would updates to the README be the key for you to give this PR an approving review?

2023-01-04 18:10 UTC, lsloan commented
@zqian, please review again. Last time you mentioned it'd be good to have more in the `README`, but I wasn't sure whether that was a comment or a requirement for PR approval.  I've not gotten any messages about it since then, so I decided to treat it as a requirement.

Please review again and give an approval so I can merge the PR or give specific feedback on what's required to make this PR mergeable.

Thanks!

2023-01-04 19:01 UTC, zqian commented
Thanks for updating the README file. I will approve the PR.

2023-01-04 19:01 UTC, zqian approved these changes

2023-01-06 15:06 UTC, merged